# Generated by Django 5.0.11 on 2026-02-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('DOCENTE', 'Docente'), ('ESTUDIANTE', 'Estudiante')], default='ESTUDIANTE', help_text='Rol funcional para el mini-LMS', max_length=20, verbose_name='Rol'),
        ),
    ]
